export const AUTH_USER = 'AUTH_USER';

// Config Action Types
// categories
export const GET_CATEGORIES_PENDING = 'GET_CATEGORIES_PENDING';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

// statuses
export const GET_STATUSES_PENDING = 'GET_STATUSES_PENDING';
export const GET_STATUSES_SUCCESS = 'GET_STATUSES_SUCCESS';
export const GET_STATUSES_FAILURE = 'GET_STATUSES_FAILURE';

// stores
export const GET_STORES_PENDING = 'GET_STORES_PENDING';
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS';
export const GET_STORES_FAILURE = 'GET_STORES_FAILURE';

//Store Item Actions
// get store items by category Id
export const GET_CATEGORY_STORE_ITEMS_PENDING =
    'GET_CATEGORY_STORE_ITEMS_PENDING';
export const GET_CATEGORY_STORE_ITEMS_FAILED =
    'GET_CATEGORY_STORE_ITEMS_FAILED';
export const GET_CATEGORY_STORE_ITEMS_SUCCESS =
    'GET_CATEGORY_STORE_ITEMS_SUCCESS';

export const RESET_STORE_ITEMS_LIST = 'RESET_STORE_ITEMS_LIST';

// get item details
export const GET_STORE_ITEM_DETAILS_PENDING = 'GET_STORE_ITEM_DETAILS_PENDING';
export const GET_STORE_ITEM_DETAILS_FAILED = 'GET_STORE_ITEM_DETAILS_FAILED';
export const GET_STORE_ITEM_DETAILS_SUCCESS = 'GET_STORE_ITEM_DETAILS_SUCCESS';

// reset store items
export const RESET_STORE_ITEM_DETAILS = 'RESET_STORE_ITEM_DETAILS';
